tasks:
  - init: apt install default-jdk
    command: echo -e " Welcome to the codebase of this project. \nFeel free to play around with the source files. \nContributions are highly appreciated. \nLeave your suggestions and feedbacks in the comment section of the repository. \nDo let me know if this project helped you in any way :) "
